---
title: "BST260 final project"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.width=20, fig.height=16)
```

\newpage

# Introduction

Nowadays, food frequency questionnaires (FFQs) have been the primary
method of dietary assessment in large cohort studies of diet and health
outcomes, because they can be self-administered, efficiently processed,
and provide data on individual intakes of both foods and nutrients over
an extended period (1). However, FFQ estimates rely on memory and hence
prone to recall bias. Other sources of error in FFQ estimates include
misinterpretation about portion size, omitting food, and so on.
Therefore, it is is critical to document the validity of FFQ estimates
(nutrients, foods, and dietary scores) and quantify the impact of these
measurement errors in the diet and disease associations.

In this project, we first evaluated the reproducibility and validity of
a FFQ in measuring three dietary scores: overall plant-based diet
indices (PDI), healthful plant-based diet index (hPDI), and unhealthful
plant-based diet index (uPDI) and their scoring components: healthful
plant foods (hplant), unhealthful plant foods (uplant), total plant
foods (tplant), and animal foods (animal) (2). The scoring methods of
these plant-based indices were shown in the **Figure 1**. This analysis
included 742 participants from the Women's Lifestyle Validation Studies
(3, 4). Participants completed a 152-item FFQ at the beginning of the
study (FFQ1) and one year later (FFQ2) and completed two weighed 7-day
dietary records (DR_wk1 and DR_wk2) six-month apart between FFQ
assessments (**Table 1**). The reproducibility of the FFQs was evaluated
by rank intraclass correlation coefficients (ICC) with two repeated FFQ
assessments (5). The validity was assessed by comparing FFQ2-derived
DQSs to those from the average of two 7DDRs (DR_avg) using Spearman rank
correlation coefficients (rs), because we are more interested in ranking
the population correctly (6, 7). Calibration coefficients were obtained
as slopes from linear regression models with FFQ estimates as
independent (predictor) variables and estimates from the average of the
two 7DDRs as dependent (outcome) variables (8-10).

We also conducted a simulation analysis to assess the effect of
measurement error in FFQ estimates on diseases risk estimation and
applied the linear approximation to correct the measurement errors (11)
. We would simulate a main study with 5,000 participants where
FFQ-derived exposures with error (Z) and outcome status (D) were
collected. Then, would sample an internal validation (n=500) from the
main study where the exposure estimates from FFQ (Z) and dietary records
(X) were collected (**Figure 2** ). We assumed FFQ estimates with
within-person errors: $Z=\lambda X+ \alpha + \epsilon_r$, where
$\epsilon_r \sim N (0, \sigma)$. The exposure-diseases associations
would be represented by a logistic model:
$logit (P(D=1|X))=\alpha+\beta X$. With FFQ-derived exposures, the
observed exposure-diseases associations would be
$logit (P(D=1|X))=\alpha_{obs}+\beta _{obs} Z$.

For the analysis part,\
1. The uncorrected coefficients $\hat{\beta_{obs}}$ and
$Var (\hat{\beta_{obs}})$ would be obtained from the main study\
2. The $\hat{\lambda}$ and $Var(\hat{\lambda})$ would be obtained from
the validation study\
3. We would apply the Linear approximation to correct the
$\hat{\beta_{obs}}$:
$$ \hat{\beta_{cor}}=\hat{\beta_{obs}}/\hat{\lambda}$$\
4. Variance of corrected coefficients would be obtained by delta method.
$$ Var(\hat{\beta_{cor}})=\frac{1}{\hat{\lambda}^2}Var(\hat{\beta_{obs}})+\frac{\hat{\beta_{obs}}^2}{\hat{\lambda}^4}Var(\hat{\lambda})$$

We would consider several scenarios with different degree of measurement
error ($\lambda$), prevalence of diseases (CI), as well as strength of
associations (odds ratio (OR)). For each combination of parameters, we
would iterate the simulation process 1,000 times to assess the RMSE of
the uncorrected and corrected $\beta$ estimates and its convergency
probability of the true $\beta$. We would also assess the direction and
degree of bias in estimated odds ratio by calculating the percentage of
bias.

# Results

## PART 1. Validation study on FFQ derived dietary indices.

We observed weak correlations between PDI and the other two plant-based
diet indices (rs=0.20 with hPDI and -0.10 with uPDI. Because higher hPDI
represented higher dietary quality and higher uPDI represented lower
dietary quality, the hPDI is inversely associated with uPDI as expected
(rs=-0.39) . The strength of correlations between plant-based diet
indices and their scoring components ranges from 0 for animal food and
PDI to 0.80 for total plants and PDI (**Figure 3**).

The FFQ-derived estimates from two assessments taken one year apart
demonstrated moderate to high reproducibility (ICC_FFQs =0.54 to 0.77)
that are slightly higher than the reproductivity of two dietary records
(ICC_DRs=0.50 to 0.68; **Table 2**). Using the average estimates of two
dietary records as the comparison method, FFQ-derived three plant-based
diet indices showed relatively high validity (rs=0.47 to 0.63), whereas
FFQ were less valid to estimate their scoring components (rs= 0.30 to
0.63; **Table 3**). We also visualized the validity results in the
**Figure 4** where we plotted the estimates from the average of the two
dietary records against FFQ estimates. Here, we found the calibration
coefficients (slopes) and R\^2 were generally higher for three
plant-based diet indices than their scoring components, suggesting the
FFQ-derived plant-based diet indices were more comparable with their
true estimates from dietary records.

## PART 2. Simulation analysis on measurement error in FFQ estimates

In the simulation procedure,\
\* We first assumed a standardized normally distributed true intake
$X_i~N(0,1)$ within the overall study population.\
\* Then, we derived the FFQ estimates with systematic and random error
$Z_i=X_i+E_i+\epsilon_i$ where half of the population over-report with
$E_i \sim N(1,(1-\lambda)/\lambda)$ and the other half of the population
under-report with $E_i \sim N(-1,(1-\lambda)/\lambda )$. All study
participants followed the same random error distribution:
$\epsilon_i \sim N(0,0.001)$.\
\* Next, we simulated the diseases status according to the binominal
distribution
$$P(D=1|X_i)=\frac{\exp(\alpha+\beta X_i)}{1+\exp(\alpha+\beta X_i)}$$
where $\alpha=logit(CI)$ and \$beta=log(OR) \$ \* The 500 observations
in the validation study were then sampled from the main study.

We developed a user-friendly algorithm to assess the impact of
measurement errors in dietary exposures on their associations with
diseases outcome (simu_resul). Using this algorithm, readers can choose
their own sets of parameters under different conditions.

In the current analysis, we mainly focused on changes of three
parameters: the degree of measurement error ($\lambda$= 0.2, 0.4,0.6,
and 0.8), the prevalence of diseases (CI=0.05, 0.1, 0.3, 0.5), and the
strength of associations (true OR= 1.2, 1.5, 2, 2.5). According to
**Figure 5** for the percentage of bias of the crude estimates under
different scenarios, we found measurement errors embedded in the
exposures tend to attenuate (bias towards the null) the ORs, and this
bias would be exacerbated with less valid FFQ-derived exposures (smaller
lambda) and stronger exposure-diseases associations (larger OR).

**Figures 6-8** show the comparison results before and after measurement
error correction. We observed the corrected beta estimates (blue) always
have smaller (red) RMSE than the uncorrected ones (**Figure 6**). In
addition, the coverage probability of true value is extremely low for
uncorrected estimates, and much higher for the corrected
estimates(**Figure 7**). This might be due to 1) more bias in the
uncorrected estimates, and 2) larger variance and wider confidence
interval for the corrected estimates. We also found the bias in ORs
decreased after applying measurement error correction (**Figure 8**).

# Conclusion

This study highlights that a 152-item, semi-quantitative FFQ is
appropriate for ranking individuals to evaluate the dietary scores.
Dietary scores derived from the FFQ showed moderate to high
reproducibility when comparing estimates one year apart, and validity
when compared with dietary scores derived from two weighed 7DDRs
collected over 1 year. However, measurement error in FFQ estimates
cannot be overlook. In the simulation analysis part, we demonstrated
that the measurement error in FFQ-derived dietary exposures could
distort the associations with health outcomes. Furthermore, we found
applying appropriate measurement error correction methods could
alleviate the bias. Therefore, in the future nutritional epidemiology
studies, it is essential to validate the dietary exposures, as well as
consider conducting measurement error correction analysis to justify
their main findings.

Our current study also has some limitations which can be improved.
First, we did find there are day-to-day random variation in dietary
records (ICC\<1), which would attenuate the validity estimates based on
spearman correlation between dietary values derived from FFQ and dietary
records. Hence, we can use Rosner. et al.'s method to account for the
random variation in dietary records (12). Second, generalizability may
be limited because our study population were all women due to the data
availability issue. We can repeat the current analysis in Men's
lifestyle validation study to further confirm our results. Third, we
have only considered single dietary exposure in the simulation analysis.
However, many dietary variables are correlated (e.g., energy intake is
positively correlated with macronutrients and food intakes) and they
could confound each other with diseases associations. Therefore, in the
real-world analysis, we would usually include several dietary variables
measured with error in the same model and need to use mthod that can
correct measurement errors for multiple variables at the same time.
Rosner. et al.'s have developed a multivariate correction method that
can handle both the error with which each variable is measured and the
correlation of errors (13).

